### ISSUE TITLE
nokogiriでDependabot alert鳴ってて渋い

### ISSUE THREAD

**Issue by sksat** [sfc-arch/sfc-arch.github.io#29]
https://github.com/sfc-arch/sfc-arch.github.io/security/dependabot/Gemfile.lock/nokogiri/open

**Comment by sksat** [comment]
これ`github-pages`が`html-pipeline 2.14.0`使っててそいつが激古`nokogiri`使ってんてカス．どうしようもないんでは．

**Comment by yumaueda** [comment]
close
