### ISSUE TITLE
About Usを更新する

### ISSUE THREAD

**Issue by akkyie** [sfc-arch/sfc-arch.github.io#7]
そろそろでは

> インターネットに関する数多くのプロトコルや規格が提案・標準化されてきた。
>
> これらの技術を集結することにより、インターネットはユーザの多様なニーズに対応してきた。
>
> 現在、次世代インターネットの基盤技術として、大容量データ伝送を実現するラムダネットワークや、 携帯電話やPDA等の移動体がインターネットへの接続性を常時確保するためのプロトコルに注目が集まっている。
>
> 今後、これらの技術が利用されることで、インターネットは多様な技術が集結することでより複雑化することが予想される。
>
> こうしたネットワークを構築・運用していくためには個々の技術に関する知識だけでなく、複雑化したネットワークをシンプルに捉える能力が必要となる。
>
> Arch はインターネットアーキテクチャの理解を深めると共に、次世代のインターネットアーキテクチャの提案・構築・運用を行う。

**Comment by yumaueda** [comment]
サイト改修に伴いupdateされた．Close
